# Generated by Django 4.0.4 on 2023-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(upload_to='./static/data/posts'),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='template',
            field=models.ImageField(blank=True, null=True, upload_to='./static/data/post_templates'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='./static/data/profile_banner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/data/user_profile'),
        ),
    ]
