# Generated by Django 4.0.4 on 2023-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='countries',
            new_name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
