# Generated by Django 4.0.4 on 2023-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_countries_user_country_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
