# Generated by Django 4.2.4 on 2023-09-12 04:49

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_portfolioprojects_project_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprojectsdetails',
            name='project_files',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
