# Generated by Django 4.2.4 on 2023-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_portfolioprojects_project_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioprojectsdetails',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='portfolioprojectsdetails',
            name='project_cover',
            field=models.ImageField(blank=True, null=True, upload_to='./static/data/project_cover'),
        ),
    ]
