# Generated by Django 4.2.4 on 2023-09-14 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_discription_portfolioprojectsdetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=500),
        ),
        migrations.DeleteModel(
            name='PortfolioProjects',
        ),
    ]
