# Generated by Django 4.2.4 on 2023-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolio_portfolio_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
