# Generated by Django 4.2.4 on 2023-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story',
            field=models.FileField(upload_to='./static/data/stories'),
        ),
    ]
