# Generated by Django 4.2.4 on 2023-08-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_stories_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(upload_to='static/data/posts'),
        ),
    ]
