# Generated by Django 4.2.4 on 2023-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_portfolioprojectsdetails_project_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioprojectsdetails',
            name='project_cover',
            field=models.ImageField(blank=True, null=True, upload_to='datas/project_cover'),
        ),
    ]
