# Generated by Django 4.2.4 on 2023-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_post_post_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.FileField(upload_to='data/posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='data/profile_banner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='data/user_profile'),
        ),
    ]
