# Generated by Django 4.2.4 on 2023-08-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_post_post_alter_user_profile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/data/user_profile'),
        ),
    ]
