# Generated by Django 4.2.4 on 2023-09-28 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
