# Generated by Django 4.2.4 on 2023-09-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='main.postdetails'),
        ),
    ]
