# Generated by Django 4.2.4 on 2023-09-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comment_post_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_details',
        ),
    ]
