# Generated by Django 4.2.4 on 2023-09-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
