# Generated by Django 4.2.4 on 2023-09-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.TextField(choices=[('freelancer', 'freelancer'), ('job', 'job')])),
                ('flexibility', models.TextField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')])),
                ('domain', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='portfolio_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProjectsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('discription', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('tools_used', models.TextField(blank=True, null=True)),
                ('project_cover', models.ImageField(upload_to='./static/data/project_cover')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appreciations', models.ManyToManyField(blank=True, related_name='appreciations', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main.portfolio')),
                ('views', models.ManyToManyField(blank=True, related_name='portfolio_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_files', models.FileField(blank=True, null=True, upload_to='./static/data/project_files')),
                ('project_files_text', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('portfolio_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_details', to='main.portfolioprojectsdetails')),
            ],
        ),
    ]
