# Generated by Django 4.2.4 on 2023-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_portfolio_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='portfolio_user',
        ),
    ]
