def degrees():
    return[
    ('BSc', 'Bachelor of Science (BSc)'),
    ('BA', 'Bachelor of Arts (BA)'),
    ('BEng', 'Bachelor of Engineering (BEng)'),
    ('BFA', 'Bachelor of Fine Arts (BFA)'),
    ('BBA', 'Bachelor of Business Administration (BBA)'),
    ('LLB', 'Bachelor of Laws (LLB)'),
    ('BEd', 'Bachelor of Education (BEd)'),
    ('BSW', 'Bachelor of Social Work (BSW)'),
    ('MSc', 'Master of Science (MSc)'),
    ('MA', 'Master of Arts (MA)'),
    ('MEng', 'Master of Engineering (MEng)'),
    ('MFA', 'Master of Fine Arts (MFA)'),
    ('MBA', 'Master of Business Administration (MBA)'),
    ('PhD', 'Doctor of Philosophy (PhD)'),
    ('MD', 'Doctor of Medicine (MD)'),
    ('DDS', 'Doctor of Dental Surgery (DDS)'),
    ('PharmD', 'Doctor of Pharmacy (PharmD)'),
    ('JD', 'Juris Doctor (JD)'),
    ('EdD', 'Doctor of Education (EdD)'),
    ('PsyD', 'Doctor of Psychology (PsyD)'),
    ('DNP', 'Doctor of Nursing Practice (DNP)'),
    ('DVM', 'Doctor of Veterinary Medicine (DVM)'),
    ('DPT', 'Doctor of Physical Therapy (DPT)'),
    ('MPH', 'Master of Public Health (MPH)'),
    ('MSW', 'Master of Social Work (MSW)'),
    ('ScD', 'Doctor of Science (ScD)'),
    ('DMin', 'Doctor of Ministry (DMin)'),
    ('DScPT', 'Doctor of Science in Physical Therapy (DScPT)'),
    ('EdD', 'Doctor of Education (EdD)'),
    ('DFA', 'Doctor of Fine Arts (DFA)'),
    ('EngD', 'Doctor of Engineering (EngD)'),
    ('DBA', 'Doctor of Business Administration (DBA)'),
    ('DSocSc', 'Doctor of Social Science (DSocSc)'),
    ('DTech', 'Doctor of Technology (DTech)'),
    ('DPA', 'Doctor of Public Administration (DPA)'),
]

def branches():
    return {
    "Associate's Degree": [
        ('CS', 'Computer Science'),
        ('IT', 'Information Technology'),
        ('BA', 'Business Administration'),
        ('CJ', 'Criminal Justice'),
        ('HM', 'Healthcare Management'),
        ('GS', 'General Studies'),
        ('LA', 'Liberal Arts'),
        ('ECE', 'Early Childhood Education'),
        ('SW', 'Social Work'),
    ],
    "Bachelor's Degree": [
        ('CS', 'Computer Science'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CE', 'Civil Engineering'),
        ('ChemE', 'Chemical Engineering'),
        ('BME', 'Biomedical Engineering'),
        ('AE', 'Aerospace Engineering'),
        ('EnvE', 'Environmental Engineering'),
        ('IE', 'Industrial Engineering'),
        ('SE', 'Software Engineering'),
        ('IT', 'Information Technology'),
        ('DS', 'Data Science'),
        ('Physics', 'Physics'),
        ('Chemistry', 'Chemistry'),
        ('Biology', 'Biology'),
        ('Math', 'Mathematics'),
        ('Stats', 'Statistics'),
        ('Econ', 'Economics'),
        ('Psych', 'Psychology'),
        ('Sociology', 'Sociology'),
        ('PolSci', 'Political Science'),
        ('History', 'History'),
        ('English', 'English'),
        ('FL', 'Foreign Languages'),
        ('BA', 'Business Administration'),
        ('Finance', 'Finance'),
        ('Marketing', 'Marketing'),
        ('Accounting', 'Accounting'),
        ('IR', 'International Relations'),
        ('Law', 'Law'),
        ('Medicine', 'Medicine'),
        ('Nursing', 'Nursing'),
        ('Pharmacy', 'Pharmacy'),
        ('Dentistry', 'Dentistry'),
        ('Architecture', 'Architecture'),
        ('FineArts', 'Fine Arts'),
        ('Music', 'Music'),
        ('FilmStudies', 'Film Studies'),
        ('Philosophy', 'Philosophy'),
        ('ReligiousStudies', 'Religious Studies'),
        ('Anthropology', 'Anthropology'),
        ('Geography', 'Geography'),
        ('Education', 'Education'),
        ('PE', 'Physical Education'),
        ('EnvSci', 'Environmental Science'),
        ('Nutrition', 'Nutrition'),
        ('Journalism', 'Journalism'),
        ('CommStudies', 'Communication Studies'),
        ('SW', 'Social Work'),
        ('PublicHealth', 'Public Health'),
    ],
    "Master's Degree": [
        ('CS', 'Computer Science'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CE', 'Civil Engineering'),
        ('ChemE', 'Chemical Engineering'),
        ('BME', 'Biomedical Engineering'),
        ('AE', 'Aerospace Engineering'),
        ('EnvE', 'Environmental Engineering'),
        ('IE', 'Industrial Engineering'),
        ('SE', 'Software Engineering'),
        ('IT', 'Information Technology'),
        ('DS', 'Data Science'),
        ('Physics', 'Physics'),
        ('Chemistry', 'Chemistry'),
        ('Biology', 'Biology'),
        ('Math', 'Mathematics'),
        ('Stats', 'Statistics'),
        ('Econ', 'Economics'),
        ('Psych', 'Psychology'),
        ('Sociology', 'Sociology'),
        ('PolSci', 'Political Science'),
        ('History', 'History'),
        ('English', 'English'),
        ('FL', 'Foreign Languages'),
        ('BA', 'Business Administration'),
        ('Finance', 'Finance'),
        ('Marketing', 'Marketing'),
        ('Accounting', 'Accounting'),
        ('IR', 'International Relations'),
        ('Law', 'Law'),
        ('Medicine', 'Medicine'),
        ('Nursing', 'Nursing'),
        ('Pharmacy', 'Pharmacy'),
        ('Dentistry', 'Dentistry'),
        ('Architecture', 'Architecture'),
        ('FineArts', 'Fine Arts'),
        ('Music', 'Music'),
        ('FilmStudies', 'Film Studies'),
        ('Philosophy', 'Philosophy'),
        ('ReligiousStudies', 'Religious Studies'),
        ('Anthropology', 'Anthropology'),
        ('Geography', 'Geography'),
        ('Education', 'Education'),
        ('PE', 'Physical Education'),
        ('EnvSci', 'Environmental Science'),
        ('Nutrition', 'Nutrition'),
        ('Journalism', 'Journalism'),
        ('CommStudies', 'Communication Studies'),
        ('SW', 'Social Work'),
        ('PublicHealth', 'Public Health'),
        ('MBA', 'Master of Business Administration (MBA)'),
        ('MSc', 'Master of Science (M.Sc.)'),
        ('MA', 'Master of Arts (M.A.)'),
        ('MEd', 'Master of Education (M.Ed.)'),
        ('MEng', 'Master of Engineering (M.Eng.)'),
        ('MFA', 'Master of Fine Arts (MFA)'),
        ('MPH', 'Master of Public Health (MPH)'),
        ('MSW', 'Master of Social Work (MSW)'),
    ],
    "Doctorate (Ph.D.)": [
        ('CS', 'Computer Science'),
        ('EE', 'Electrical Engineering'),
        ('ME', 'Mechanical Engineering'),
        ('CE', 'Civil Engineering'),
        ('ChemE', 'Chemical Engineering'),
        ('BME', 'Biomedical Engineering'),
        ('AE', 'Aerospace Engineering'),
        ('EnvE', 'Environmental Engineering'),
        ('IE', 'Industrial Engineering'),
        ('SE', 'Software Engineering'),
        ('IT', 'Information Technology'),
        ('DS', 'Data Science'),
        ('Physics', 'Physics'),
        ('Chemistry', 'Chemistry'),
        ('Biology', 'Biology'),
        ('Math', 'Mathematics'),
        ('Stats', 'Statistics'),
        ('Econ', 'Economics'),
        ('Psych', 'Psychology'),
        ('Sociology', 'Sociology'),
        ('PolSci', 'Political Science'),
        ('History', 'History'),
        ('English', 'English'),
        ('FL', 'Foreign Languages'),
        ('BA', 'Business Administration'),
        ('Finance', 'Finance'),
        ('Marketing', 'Marketing'),
        ('Accounting', 'Accounting'),
        ('IR', 'International Relations'),
        ('Law', 'Law'),
        ('Medicine', 'Medicine'),
        ('Nursing', 'Nursing'),
        ('Pharmacy', 'Pharmacy'),
        ('Dentistry', 'Dentistry'),
        ('Architecture', 'Architecture'),
        ('FineArts', 'Fine Arts'),
        ('Music', 'Music'),
        ('FilmStudies', 'Film Studies'),
        ('Philosophy', 'Philosophy'),
        ('ReligiousStudies', 'Religious Studies'),
        ('Anthropology', 'Anthropology'),
        ('Geography', 'Geography'),
        ('Education', 'Education'),
        ('PE', 'Physical Education'),
        ('EnvSci', 'Environmental Science'),
        ('Nutrition', 'Nutrition'),
        ('Journalism', 'Journalism'),
        ('CommStudies', 'Communication Studies'),
        ('SW', 'Social Work'),
        ('PublicHealth', 'Public Health'),
        ('Ph.D.', 'Doctor of Philosophy (Ph.D.)'),
        ('Ed.D.', 'Doctor of Education (Ed.D.)'),
        ('DBA', 'Doctor of Business Administration (DBA)'),
        ('Psy.D.', 'Doctor of Psychology (Psy.D.)'),
        ('DNP', 'Doctor of Nursing Practice (DNP)'),
        ('DVM', 'Doctor of Veterinary Medicine (DVM)'),
        ('DPT', 'Doctor of Physical Therapy (DPT)'),
        ('Honorary Ph.D.', 'Doctor of Philosophy (Honorary Ph.D.)'),
        ('L.H.D. or D.H.L.', 'Doctor of Humane Letters (L.H.D. or D.H.L.)'),
        ('Sc.D.', 'Doctor of Science (Sc.D.)'),
        ('D.Mus.', 'Doctor of Music (D.Mus.)'),
        ('DFA', 'Doctor of Fine Arts (DFA)'),
        ('Eng.D.', 'Doctor of Engineering (Eng.D.)'),
        ('DPA', 'Doctor of Public Administration (DPA)'),
        ('DSocSc', 'Doctor of Social Science (DSocSc)'),
        ('D.Tech.', 'Doctor of Technology (D.Tech.)'),
    ],
    "Others": [
        ('Certificate', 'Certificate Programs'),
        ('Diploma', 'Diploma Programs'),
        ('Postgraduate Diplomas', 'Postgraduate Diplomas'),
        ('Professional Degrees', 'Professional Degrees'),
    ],
}


import pycountry

country_tuples = []

for country in pycountry.countries:
    country_id = country.alpha_2
    country_full_name = country.name
    country_tuples.append((country_id, country_full_name))
    
def countries():
    return country_tuples